#cloud-config

coreos:
  etcd2:
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-cluster: control1=http://10.200.1.1:2380
    proxy: on
  fleet:
    public-ip: $public_ipv4
    metadata: "role=worker,cpeer=tsc-staging1"
  units:
    - name: 00-ens4v1.network
      runtime: true
      content: |
        [Match]
        Name=ens4v1

        [Network]
        Address=10.200.3.1/24
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Unit]
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="0.0.0.0/0"'
write_files:
 - path: /etc/resolv.conf
   permissions: 0644
   owner: root
   content: |
     nameserver 169.254.169.254
     nameserver 10.240.0.1
ssh_authorized_keys:
 - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrJybGYAiSG9Z2ETblpLimDsMoZgkGRyHamecl9X4XVwtgzV6Kl37BgEO2Mhp4D3K48wqn5rRBNETV6UNZPF42epgkEKBFFffZIwLZ9ppJMr0KT21+82jPX059j5OMsz5qLv7UzCocAb/rULk5Rudkh4NXTcXly9ybHWITSJ3hLebZblBPtg5Fi/RG7WnOP+DvLNGJXt89xIvSRHJBrQ4z2zaEKICABLU5Ky6aX4MqJf+9NU15cC7NgFhL+Juhhrm2V66XxN2apikYXEyjMHjaGkJvYPVSjYplydc0WdZb++jjAqGGb0AZQrwT8kcZEk5peHC5LPyaRmTuXqQkFl9J root@tsc-registry-cbuilder1-docker-builder
